### ISSUE TITLE
Validator does not work correctly when packaged as jar within other application

### ISSUE THREAD

**Issue by JannickWeisshaupt** [itplr-kosit/validator#28] opened 2019-03-27 13:50 UTC
Following situation:
I use the Kosit Validator as library within another application, which is packaged as jar. The scenario and xsl files are included in the jar as resource files. I specified the URI to the scenario correctly so that the scenario file within the jar is used. When the Validator is build it tries to load the xsl files, which are specified in the scenario file. The constructor fails because the URI cannot be resolved
The error is file not found because line 117 in ContentRepository is not correctly working
`    return new StreamSource(this.repository.resolve(source).toASCIIString());
`

**Comment by apenski** [comment] 2019-05-06 08:31
This is a known limitation and we plan to support loading scenario-content from a jar file. 
However, since JAR-URIs fail to resolve relative paths correctly, it is not as easy as 'return a correct stream source in ContentRepository'.  This would result in errors loading transitive resources like references schema files.

**Comment by apenski** [comment] 2019-05-08 07:11
I prepared a [branch](https://github.com/apenski/validator/tree/%2314_Load_from_JAR_vereinfacht) with this. This must be testet now. Beta testers welcome!

I should be sufficient to provide a valid JAR-URI to initialize ContentRepository and/or ScenarioRepository.

**Comment by AM-csx** [comment] 2019-06-19 11:21
Unfortunately, we have the same problem with all previous releases. It also doesn't work with your development [branch](https://github.com/apenski/validator/tree/%2314_Load_from_JAR_vereinfacht).

First some details about our use case and the technical implementation:
- We want to use the KoSIT validator as a library. 
- Our actual application is a Spring Boot application.
- We get the "KoSIT validator"-library as dependency in Maven.
- For each configuration version of the XRechnung (https://github.com/itplr-kosit/validator-configuration-xrechnung/releases) we have its own subfolder in our resource folder of our Spring Boot application.

Here is a snippet with the concrete example (It is relatively easy to reproduce.): [https://gist.github.com/AM-csx/63f63c5166345cb398ddcb3a90287037](https://gist.github.com/AM-csx/63f63c5166345cb398ddcb3a90287037)

When we launch the application from our development environment, everything works fine because our application is still "exploded":
![KositValidationDemoApplication_succesful_from_intellij](https://user-images.githubusercontent.com/51994389/59760902-a0f88480-9293-11e9-985b-8690b66596ea.png)

If we build our Spring Boot application now as executable JAR (mvn package) and start it, we get the following errors during the initialization:
[KositValidationDemoApplication_failed_from_jar.log](https://github.com/itplr-kosit/validator/files/3305770/KositValidationDemoApplication_failed_from_jar.log)

**Comment by apenski** [comment] 2019-06-20 09:27
Thanks for beta testing the branch. Actual I missed the default deduction of the repository location when not configured explicitly. I created a fix in 3edb23bcfd54 and was successfull loading the resources with you provided snippet.

Can you please test the [branch](https://github.com/itplr-kosit/validator/compare/%2314_Load_from_JAR_einfacher) again (moved to this repo)

**Comment by AM-csx** [comment] 2019-06-25 08:09
Thank you for the quick reaction :)
		
I can confirm that this issue has been resolved with this [branch ](https://github.com/itplr-kosit/validator/compare/%2314_Load_from_JAR_einfacher)👍 
		
What are your release plans for a new Validator version? Can you give an approximate time frame?

**Comment by apenski** [comment] 2019-06-28 12:02
we plan to release within July. The branch is merged to the master now

**Closed** 2019-07-03 08:26 UTC
Labels: bug, help wanted
